### ISSUE TITLE
.joplin-blog.json configuration doubts.

### ISSUE THREAD

**Issue by arjunbazinga** [rxliuli/joplin-blog#1]
Hello! 

This project looks like exactly what I was looking for!

I was trying to configure .joplin-blog.json , i'm not sure what 

```
joplinProfilePath | string | joplin personal folder

tag | string | joplin's blog tag




```

refers to, can you please give an example? 

I looked at the hexo and vue-press example tutorials but couldn't find the .joplin-blog.json file.

Thanks!

Arjun

**Comment by rxliuli** [comment]
I have submitted the configuration file of the test environment, you can refer to it

https://github.com/rxliuli/joplin-blog/blob/dev/tutorials/hexo-example/.joplin-blog.json
