### ISSUE TITLE
exporting error

### ISSUE THREAD

**Issue by geeemok** [rxliuli/joplin-blog#5]
Here is the error log

(node:8772) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'includes' of undefined
    at JoplinHexoIntegrated.<anonymous> (E:\Hexo\node_modules\joplin-blog\dist\JoplinHexoIntegrated.js:105:53)
    at Generator.next (<anonymous>)
    at fulfilled (E:\Hexo\node_modules\joplin-blog\dist\JoplinHexoIntegrated.js:24:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:8772) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:8772) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by rxliuli** [comment]
joplin v0.1.5 has been released, you can update it
https://www.npmjs.com/package/joplin-blog

**Comment by geeemok** [comment]
thanks a lot , it works! and need run as admin.
hope you find a good job! you are the best!
