### ISSUE TITLE
求助：markdown 图片在post page 页面不加载

### ISSUE THREAD

**Issue by geeemok** [rxliuli/joplin-blog#7]
用本插件（joplin-blog）批量导出笔记之后，所有图片的地址都是(../resource/xxx.jpg)，
这个在被hexo g以后，生成的页面中。
1.主页图片会显示，因为该文件夹被导入到了resourse里面，相对位置正确（主页index和resourse都在根目录）
2.但是点击*阅读更多*以后，图片就不显示了，相对位置不对（post的index存在以日期为格式的文件夹里，而resourse在根目录）

求问博主图片都是怎么插入的

**Comment by rxliuli** [comment]
这是一个 pr 导致的，稍晚一点吾辈撤回回去。
吾辈没有问题的原因在于吾辈的文章链接是 /p/:id，所以没有目录问题

**Comment by geeemok** [comment]
多谢，我把永久链接改成permalink: :title-:hash/，就只有一级目录了。

**Comment by rxliuli** [comment]
已发布 v0.1.6，更新之后将不会受到相对路径影响，但同时，会引入另一个在本地查看时的问题，参考：https://github.com/rxliuli/joplin-blog/pull/4

https://www.npmjs.com/package/joplin-blog
